### ISSUE TITLE
Cannot be build in the new version of NextJS@13.5

### ISSUE THREAD

**Issue by wacanam** [viclafouch/mui-file-input#43]
```
 ⨯ C:\Users\wacanam\ReactJS\projects\HIMS.Processing-FrontEnd\node_modules\mui-file-input\dist\mui-file-inp
ut.es.js:1
import { jsxs as f, jsx as o } from "react/jsx-runtime";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:74:18)
    at wrapSafe (node:internal/modules/cjs/loader:1141:20)
    at Module._compile (node:internal/modules/cjs/loader:1182:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at mod.require (C:\Users\wacanam\ReactJS\projects\HIMS.Processing-FrontEnd\node_modules\next\dist\serve
r\require-hook.js:64:28)
    at require (node:internal/modules/cjs/helpers:103:18)
    at mui-file-input (C:\Users\wacanam\ReactJS\projects\HIMS.Processing-FrontEnd\.next\server\pages\client
\files.js:4169:18)
    at __webpack_require__ (C:\Users\wacanam\ReactJS\projects\HIMS.Processing-FrontEnd\.next\server\webpack
-runtime.js:33:43)
    at eval (webpack-internal:///./components/CreateAttachmentModal.tsx:43:73)
    at __webpack_require__.a (C:\Users\wacanam\ReactJS\projects\HIMS.Processing-FrontEnd\.next\server\webpack-runtime.js:97:13)
    at eval (webpack-internal:///./components/CreateAttachmentModal.tsx:1:21)
    at __webpack_require__.a (C:\Users\wacanam\ReactJS\projects\HIMS.Processing-FrontEnd\.next\server\webpack-runtime.js:97:13)
    at eval (webpack-internal:///./components/CreateAttachmentModal.tsx:1:21)
    at ./components/CreateAttachmentModal.tsx (C:\Users\wacanam\ReactJS\projects\HIMS.Processing-FrontEnd\.next\server\pages\client\files.js:2355:1) {
    at ./components/CreateAttachmentModal.tsx (C:\Users\wacanam\ReactJS\projects\HIMS.Processing-FrontEnd\.next\server\pages\client\files.js:2355:1) {
    at ./components/CreateAttachmentModal.tsx (C:\Users\wacanam\ReactJS\projects\HIMS.Processing-FrontEnd\.next\server\pages\client\files.js:2355:1) {
    at ./components/CreateAttachmentModal.tsx (C:\Users\wacanam\ReactJS\projects\HIMS.Processing-FrontEnd\.next\server\pages\client\files.js:2355:1) {
    at ./components/CreateAttachmentModal.tsx (C:\Users\wacanam\ReactJS\projects\HIMS.Processing-FrontEnd\.
next\server\pages\client\files.js:2355:1) {
  page: '/client/files'
}
}
```

**Comment by viclafouch** [comment]
Duplicate with https://github.com/viclafouch/mui-file-input/issues/38
